title: communication technology
author: Jiya Gijo
email: jgijo1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
 this is something I made for comm. tech. 
theme: minima
# social links
twitter_username: @jiyag12
github_username:  @jiyag12

show_excerpts: true # set to false to remove excerpts on the homepage
